% Probability and Statistics for Computer Scientists P129

N = 16577;
% Binomial distribution parameters
C = 250; p = 0.3;
% Geometric distribution parameter
q = 0.15;
% Gamma distribution parameters
alph = 10; lambda = 3;

TotalTime = zeros(N, 1); % Save totaltime for each run
for k = 1:N;
    % total number of active users, generated by sum of bernoulli trials
    X = sum(rand(C, 1) < p);
    % generate geometric variable using inverse transform method
    Y = ceil(log(1 - rand(X, 1)) / log(1 - q));
    % total daily number tasks
    TotalTasks = sum(Y);
    % Gamma distribution generated as sum of geometric
    T = sum(-1/lambda * log(rand(alph, TotalTasks)));
    TotalTime(k) = sum(T);
end;

P_est = TotalTime < 1440;
sum(P_est)/N
mean(TotalTime)
std(TotalTime)